development:
  adapter: postgresql
  database: gt_dev
  username: gt_admin
  password: test
  encoding: utf-8
  host: localhost

test:
  adapter: postgresql
  database: gt_test
  username: gt_admin
  password: test
  encoding: utf-8
  host: localhost